import pandas as pd
df = pd.read_csv("data/telco_churn_raw.csv")
print(df.shape)
print(df.head())
print(df.columns.tolist())
print(df.info())
print(df[df['TotalCharges']==' '])
df['TotalCharges']= df['TotalCharges'].replace(' ', '0')
df['TotalCharges']= df['TotalCharges'].astype(float)
print(df['TotalCharges'].dtype)
print(df['TotalCharges'].isnull().sum())
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
    print(f"\n{col}:")
    print(df[col].unique())
print(df['Churn'].value_counts())
print(df['Churn'].value_counts(normalize=True)*100)
print("\n--- Churn by Contract Type ---")
print(df.groupby('Contract')['Churn'].value_counts(normalize=True).unstack()*100)
print("\n--- Churn by Internet Service ---")
print(df.groupby('InternetService')['Churn'].value_counts(normalize=True).unstack() * 100)
print("\n--- Average tenure: churned vs stayed ---")
print(df.groupby('Churn')['tenure'].mean())
print("\n--- Average Monthly Charges: churned vs stayed ---")
print(df.groupby('Churn')['MonthlyCharges'].mean())
df.to_csv("data/telco_churn_cleaned.csv", index=False)
print("Cleaned data saved.")